### ISSUE TITLE
Skeleton App

### ISSUE THREAD

**Issue by olegood** [olegood/muzapp#1]
### Description
Upload skeleton project, main directories layout.

### Tasks

- [ ] create 'resource' service
- [ ] create 'song' service
- [ ] create 'processor' service
